site_name: Jarvis Documentation
nav:
    - Home: index.md
theme:
    name: material
    favicon: 'img/favicon.ico'
markdown_extensions:
    - codehilite:
        linenums: true
    - admonition
    - footnotes
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde